### ISSUE TITLE
Don’t Organize by file type!

### ISSUE THREAD

**Issue by overlineink** [Donnerstagnacht/leftlife#1]
Don’t Organize by file type e.g. _directives/, services/_, etc.
The reason for this is that when we are looking to make a change, we often need to
change a few related files at once. When organizing by file type we need to
traverse the folder tree multiple times to locate the needed files.

Rather we suggest that the code base be organized by domain and include all the
related files together e.g. airline which includes state, ui components, etc. inside a
single grouping folder. This allows a developer to work on related files without
needing to traverse the folder tree often.

**Comment by Donnerstagnacht** [comment]
I had an issue committing stuff. Do you only mean the core module?  What would you change exactly since I think that we most of the models and services are used by multiple url-views?

**Comment by overlineink** [comment]
I mean this:
![tobi](https://user-images.githubusercontent.com/24974840/53346753-93e40e00-390f-11e9-8ab0-469f8f301b10.jpg)

Can I refactor that? I found others potential issues that I'll share with you on Slack.
